global using Xunit;
global using Moq;
global using FluentAssertions;
global using Infrastructure.Services.Interfaces;
global using Microsoft.Extensions.Logging;
global using Catalog.Host.Services.Interfaces;
global using Catalog.Host.Data;
global using Catalog.Host.Data.Entities;
global using Microsoft.EntityFrameworkCore.Storage;